data_paths:
    raw_data_path:               '/opt/ml/processing/dummy-model/data/raw_data/'
    preprocessed_data_path:      '/opt/ml/processing/dummy-model/data/preprocessed_data/'
    inferenced_data_path:        '/opt/ml/processing/dummy-model/data/inferenced_data/'

artifact_paths:
    base_path:                   '/opt/ml/processing/dummy-model/artifacts/'
    training_dataset_path:       '/opt/ml/processing/dummy-model/artifacts/training_dataset/'
    scaler_path:                 '/opt/ml/processing/dummy-model/artifacts/preprocessing/'
    model_path:                  '/opt/ml/processing/dummy-model/artifacts/models/'

mlflow:
  run_id_txt_path:               '/opt/ml/processing/dummy-model/mlflow/mlflow_run_id.txt'
  tracking_server_url:           'https://gda-dev-mlflow-tracking.docusignhq.com'
