data_paths:
    raw_data_path:               'dummy_model/training/data/raw_data/'
    preprocessed_data_path:      'dummy_model/training/data/preprocessed_data/'

artifact_paths:
    base_path:                   'dummy_model/training/artifacts/'
    training_dataset_path:       'dummy_model/training/artifacts/training_dataset/'
    scaler_path:                 'dummy_model/training/artifacts/preprocessing/'
    model_path:                  'dummy_model/training/artifacts/models/'

mlflow:
  run_id_txt_path:               'dummy_model/training/mlflow/mlflow_run_id.txt'
  tracking_server_url:           'http://127.0.0.1:5000/'
