data_paths:
    raw_data_path:              'dummy_model/batch_inference/data/raw_data/'
    preprocessed_data_path:     'dummy_model/batch_inference/data/preprocessed_data/'
    inferenced_data_path:       'dummy_model/batch_inference/data/inferenced_data/'
    postprocessed_data_path:    'dummy_model/batch_inference/data/postprocessed_data/'
artifact_paths:
    base_path:                  'dummy_model/batch_inference/artifacts/'
    scaler_path:                'dummy_model/batch_inference/artifacts/preprocessing/'
    model_path:                 'dummy_model/batch_inference/artifacts/models/'
