num_vars:
  - name: NUMERICAL_1
    to_scale: True
  - name: NUMERICAL_2
    to_scale: False
  - name: NUMERICAL_3
    to_scale: True

cat_vars:
  - name: CATEGORICAL_1
    to_one_hot_encode: True
  - name: CATEGORICAL_2
    to_one_hot_encode: True

target_var:
  name: TARGET
  to_scale: False
